import type { MergeEntityKind } from "./types.js";

/**
 * Framework-aware file content generators.
 * These produce minimal, valid stubs — real content generation
 * belongs to a higher-level code-generation pipeline.
 */

export interface StubContext {
  name: string;
  path: string;
  framework: string;
  entityKind: MergeEntityKind;
  metadata: Record<string, unknown>;
}

// ─── Route / page stubs ───────────────────────────────────────────────────────

function reactPageStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `export default function ${displayName}() {`,
    `  return (`,
    `    <main>`,
    `      <h1>${displayName}</h1>`,
    `      {/* TODO: populate with merged content */}`,
    `    </main>`,
    `  );`,
    `}`,
  ].join("\n");
}

function nextjsPageStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `import type { Metadata } from "next";`,
    ``,
    `export const metadata: Metadata = {`,
    `  title: "${displayName}",`,
    `};`,
    ``,
    `export default function ${displayName}Page() {`,
    `  return (`,
    `    <main>`,
    `      <h1>${displayName}</h1>`,
    `      {/* TODO: populate with merged content */}`,
    `    </main>`,
    `  );`,
    `}`,
  ].join("\n");
}

function astroPageStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `---`,
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    `const title = "${displayName}";`,
    `---`,
    ``,
    `<html lang="en">`,
    `  <head><title>{title}</title></head>`,
    `  <body>`,
    `    <main>`,
    `      <h1>{title}</h1>`,
    `      <!-- TODO: populate with merged content -->`,
    `    </main>`,
    `  </body>`,
    `</html>`,
  ].join("\n");
}

function htmlPageStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `<!-- AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()} -->`,
    `<!-- Source path: ${ctx.path} | Action: CREATE -->`,
    `<!DOCTYPE html>`,
    `<html lang="en">`,
    `  <head>`,
    `    <meta charset="UTF-8" />`,
    `    <meta name="viewport" content="width=device-width, initial-scale=1" />`,
    `    <title>${displayName}</title>`,
    `  </head>`,
    `  <body>`,
    `    <main>`,
    `      <h1>${displayName}</h1>`,
    `      <!-- TODO: populate with merged content -->`,
    `    </main>`,
    `  </body>`,
    `</html>`,
  ].join("\n");
}

// ─── Component stubs ──────────────────────────────────────────────────────────

function reactComponentStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `interface ${displayName}Props {`,
    `  // TODO: define props from merged content`,
    `  [key: string]: unknown;`,
    `}`,
    ``,
    `export function ${displayName}({ ...props }: ${displayName}Props) {`,
    `  return (`,
    `    <div data-component="${displayName.toLowerCase()}" {...props}>`,
    `      {/* TODO: implement component */}`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `export default ${displayName};`,
  ].join("\n");
}

function astroComponentStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `---`,
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    `interface Props {`,
    `  // TODO: define props from merged content`,
    `  [key: string]: unknown;`,
    `}`,
    `const { ...props } = Astro.props;`,
    `---`,
    ``,
    `<div data-component="${displayName.toLowerCase()}">`,
    `  <!-- TODO: implement component -->`,
    `</div>`,
  ].join("\n");
}

// ─── Layout stubs ─────────────────────────────────────────────────────────────

function reactLayoutStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `import type { ReactNode } from "react";`,
    ``,
    `interface ${displayName}Props {`,
    `  children: ReactNode;`,
    `}`,
    ``,
    `export function ${displayName}({ children }: ${displayName}Props) {`,
    `  return (`,
    `    <div data-layout="${displayName.toLowerCase()}">`,
    `      {/* TODO: add header/footer/nav from merged content */}`,
    `      <main>{children}</main>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `export default ${displayName};`,
  ].join("\n");
}

function nextjsLayoutStub(ctx: StubContext): string {
  const displayName = toComponentName(ctx.name);
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `export default function ${displayName}Layout({`,
    `  children,`,
    `}: {`,
    `  children: React.ReactNode;`,
    `}) {`,
    `  return (`,
    `    <div data-layout="${displayName.toLowerCase()}">`,
    `      {/* TODO: add header/footer/nav from merged content */}`,
    `      {children}`,
    `    </div>`,
    `  );`,
    `}`,
  ].join("\n");
}

// ─── API stubs ────────────────────────────────────────────────────────────────

function expressApiStub(ctx: StubContext): string {
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `import { Router } from "express";`,
    ``,
    `const router = Router();`,
    ``,
    `router.get("${ctx.path}", async (req, res) => {`,
    `  // TODO: implement handler for merged API endpoint`,
    `  res.json({ ok: true });`,
    `});`,
    ``,
    `export default router;`,
  ].join("\n");
}

function nextjsApiStub(ctx: StubContext): string {
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    ``,
    `import type { NextRequest } from "next/server";`,
    ``,
    `export async function GET(_req: NextRequest) {`,
    `  // TODO: implement handler for merged API endpoint`,
    `  return Response.json({ ok: true });`,
    `}`,
  ].join("\n");
}

// ─── DataSource stubs ─────────────────────────────────────────────────────────

function dataSourceStub(ctx: StubContext): string {
  return [
    `// AUTO-GENERATED by merge-execution-engine — ${new Date().toISOString()}`,
    `// Source path: ${ctx.path}`,
    `// Action: CREATE`,
    `// Data source: ${String(ctx.metadata["provider"] ?? "unknown")}`,
    ``,
    `// TODO: configure data source connection`,
    `export const ${toCamelCase(ctx.name)}Config = {`,
    `  provider: "${String(ctx.metadata["provider"] ?? "unknown")}",`,
    `  // Add connection details here`,
    `};`,
  ].join("\n");
}

// ─── UPDATE merge block ───────────────────────────────────────────────────────

export function buildUpdateBlock(
  existingContent: string,
  ctx: StubContext
): string {
  const fence = "=".repeat(60);
  const timestamp = new Date().toISOString();
  return [
    existingContent,
    ``,
    `// ${"─".repeat(58)}`,
    `// MERGE UPDATE — ${timestamp}`,
    `// Decision: ${ctx.metadata["decisionId"] ?? "unknown"}`,
    `// Source: ${ctx.path}`,
    `// Reason: ${String(ctx.metadata["reason"] ?? "content update from manifest")}`,
    `// ${fence}`,
    `// TODO: review and integrate the following changes from the merged manifest.`,
    `// The original content above is preserved; apply selective updates below.`,
    `// ${"─".repeat(58)}`,
  ].join("\n");
}

// ─── EXTEND data entry ────────────────────────────────────────────────────────

export function buildExtendEntry(ctx: StubContext): string {
  const timestamp = new Date().toISOString();
  return [
    ``,
    `// ─── EXTEND ENTRY — ${timestamp} ────────────────────────────────`,
    `// Decision: ${ctx.metadata["decisionId"] ?? "unknown"}`,
    `// Entity: ${ctx.name} (${ctx.entityKind})`,
    `// Source path: ${ctx.path}`,
    `// TODO: the following entry was identified as fitting an existing`,
    `// dynamic route. Integrate it into your data layer or CMS.`,
    `export const ${toCamelCase(ctx.name)}Entry = {`,
    `  slug: "${toSlug(ctx.name)}",`,
    `  title: "${ctx.name}",`,
    `  path: "${ctx.path}",`,
    `  // TODO: populate fields from merged manifest content`,
    `};`,
  ].join("\n");
}

// ─── ARCHIVE header ───────────────────────────────────────────────────────────

export function buildArchiveHeader(
  originalContent: string,
  ctx: StubContext
): string {
  const timestamp = new Date().toISOString();
  const lines = [
    `// ╔══════════════════════════════════════════════════════════════╗`,
    `// ║  ARCHIVED by merge-execution-engine — ${timestamp}  ║`,
    `// ║  Original path: ${ctx.path.padEnd(44)}║`,
    `// ║  Reason: ${String(ctx.metadata["reason"] ?? "no scraped content maps to this entity").slice(0, 50).padEnd(52)}║`,
    `// ║  Decision: ${String(ctx.metadata["decisionId"] ?? "unknown").padEnd(49)}║`,
    `// ╚══════════════════════════════════════════════════════════════╝`,
    ``,
  ];
  return lines.join("\n") + originalContent;
}

// ─── Dispatch ─────────────────────────────────────────────────────────────────

export function generateCreateStub(ctx: StubContext): { content: string; ext: string } {
  const fw = ctx.framework.toLowerCase();

  switch (ctx.entityKind) {
    case "route":
    case "layout": {
      if (fw === "nextjs") {
        const content = ctx.entityKind === "layout"
          ? nextjsLayoutStub(ctx)
          : nextjsPageStub(ctx);
        return { content, ext: "tsx" };
      }
      if (fw === "astro") {
        const content = astroPageStub(ctx);
        return { content, ext: "astro" };
      }
      if (fw === "react") {
        const content = ctx.entityKind === "layout"
          ? reactLayoutStub(ctx)
          : reactPageStub(ctx);
        return { content, ext: "tsx" };
      }
      return { content: htmlPageStub(ctx), ext: "html" };
    }

    case "component": {
      if (fw === "astro") {
        return { content: astroComponentStub(ctx), ext: "astro" };
      }
      return { content: reactComponentStub(ctx), ext: "tsx" };
    }

    case "api": {
      if (fw === "nextjs") {
        return { content: nextjsApiStub(ctx), ext: "ts" };
      }
      return { content: expressApiStub(ctx), ext: "ts" };
    }

    case "datasource": {
      return { content: dataSourceStub(ctx), ext: "ts" };
    }

    default: {
      return { content: reactComponentStub(ctx), ext: "tsx" };
    }
  }
}

// ─── Path derivation ──────────────────────────────────────────────────────────

export function deriveFilePath(
  ctx: StubContext,
  ext: string
): string {
  const fw = ctx.framework.toLowerCase();
  const slug = toSlug(ctx.name);
  const srcPath = ctx.path && ctx.path !== "/" ? ctx.path : `/${slug}`;

  switch (ctx.entityKind) {
    case "route":
      if (fw === "nextjs") return `app${srcPath}/page.${ext}`;
      if (fw === "astro") return `src/pages${srcPath}.${ext}`;
      return `src/pages${srcPath}.${ext}`;

    case "layout":
      if (fw === "nextjs") return `app${srcPath}/layout.${ext}`;
      return `src/layouts/${toComponentName(ctx.name)}.${ext}`;

    case "component":
      return `src/components/${toComponentName(ctx.name)}.${ext}`;

    case "api":
      if (fw === "nextjs") return `app/api${srcPath}/route.${ext}`;
      return `src/routes/api${srcPath}.${ext}`;

    case "datasource":
      return `src/lib/${toCamelCase(ctx.name)}.${ext}`;

    default:
      return `src/generated/${slug}.${ext}`;
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toComponentName(raw: string): string {
  return raw
    .replace(/[^a-zA-Z0-9\s_-]/g, "")
    .split(/[\s_-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function toSlug(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/[\s]+/g, "-");
}

function toCamelCase(raw: string): string {
  const parts = raw
    .replace(/[^a-zA-Z0-9\s_-]/g, "")
    .split(/[\s_-]+/);
  return parts
    .map((w, i) =>
      i === 0
        ? w.toLowerCase()
        : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
    )
    .join("");
}
