import type { DeploymentAdapter, DeploymentContext, DeploymentPlan } from "../types.js";

export const wordpressAdapter: DeploymentAdapter = {
  framework: "wordpress",

  generate(ctx: DeploymentContext): DeploymentPlan {
    const now = new Date().toISOString();
    return {
      version: "1.0",
      generatedAt: now,
      framework: "wordpress",
      frameworkVersion: ctx.version,
      sourceUrl: ctx.sourceUrl,
      summary:
        "WordPress site — managed WordPress hosts (WP Engine, Kinsta) eliminate server management. Docker with the official image enables self-hosting. WP-CLI automates plugin, theme, and migration tasks.",

      hostingOptions: [
        {
          name: "WP Engine",
          provider: "wpengine",
          tier: "pro",
          url: "https://wpengine.com",
          recommended: true,
          deployMethod: "git",
          config: {
            phpVersion: "8.3",
            mysqlVersion: "8.0",
            cdnIncluded: "true",
          },
          notes: [
            "Fully managed: automated backups, updates, and security scanning.",
            "Deploy via Git push or SFTP — WP Engine has a native Git integration.",
            "Built-in CDN, staging environments, and one-click site cloning.",
          ],
        },
        {
          name: "Kinsta",
          provider: "kinsta",
          tier: "pro",
          url: "https://kinsta.com",
          recommended: false,
          deployMethod: "panel",
          config: {
            phpVersion: "8.3",
            database: "MariaDB 10.6",
            caching: "Nginx + Redis",
          },
          notes: [
            "Google Cloud-based with 37 global data centers.",
            "Automated daily backups and free SSL.",
            "DevKinsta local dev tool mirrors your production environment.",
          ],
        },
        {
          name: "SiteGround",
          provider: "siteground",
          tier: "hobby",
          url: "https://siteground.com",
          recommended: false,
          deployMethod: "panel",
          config: {
            phpVersion: "8.3",
            environment: "cPanel",
          },
          notes: [
            "Budget-friendly shared hosting with a WordPress-optimized stack.",
            "One-click WordPress install via cPanel.",
            "SG Optimizer plugin for caching and CDN.",
          ],
        },
        {
          name: "Cloudways",
          provider: "cloudways",
          tier: "pro",
          url: "https://cloudways.com",
          recommended: false,
          deployMethod: "panel",
          config: {
            phpVersion: "8.3",
            server: "DigitalOcean / AWS / GCP",
            caching: "Varnish + Redis + Memcached",
          },
          notes: [
            "Managed cloud hosting — pick your underlying provider.",
            "Deploy from GitHub with the Git deployment add-on.",
            "Bot protection, malware scanning, and automated backups included.",
          ],
        },
        {
          name: "Docker (Self-Hosted)",
          provider: "self-hosted",
          tier: "pro",
          url: "https://hub.docker.com/_/wordpress",
          recommended: false,
          deployMethod: "docker",
          config: {
            image: "wordpress:php8.3-apache",
            dbImage: "mysql:8.0",
          },
          notes: [
            "Use the official wordpress Docker image.",
            "Persist wp-content via a named Docker volume.",
            "Use Traefik or nginx-proxy for TLS termination.",
          ],
        },
      ],

      buildConfig: {
        installCommand: "composer install --no-dev",
        buildCommand: "wp core download && wp core install",
        outputDirectory: null,
        startCommand: "apache2-foreground",
        nodeVersion: null,
        phpVersion: "8.3",
        envVars: [
          {
            name: "WORDPRESS_DB_HOST",
            required: true,
            description: "MySQL database host",
            example: "mysql:3306",
          },
          {
            name: "WORDPRESS_DB_NAME",
            required: true,
            description: "MySQL database name",
            example: "wordpress",
          },
          {
            name: "WORDPRESS_DB_USER",
            required: true,
            description: "MySQL username",
            example: "wordpress",
          },
          {
            name: "WORDPRESS_DB_PASSWORD",
            required: true,
            description: "MySQL password",
            example: null,
          },
          {
            name: "WORDPRESS_AUTH_KEY",
            required: true,
            description: "WordPress secret key — generate from https://api.wordpress.org/secret-key/1.1/salt/",
            example: null,
          },
          {
            name: "WORDPRESS_SECURE_AUTH_KEY",
            required: true,
            description: "WordPress secret key",
            example: null,
          },
          {
            name: "WORDPRESS_LOGGED_IN_KEY",
            required: true,
            description: "WordPress secret key",
            example: null,
          },
          {
            name: "WORDPRESS_NONCE_KEY",
            required: true,
            description: "WordPress secret key",
            example: null,
          },
          {
            name: "WORDPRESS_TABLE_PREFIX",
            required: false,
            description: "Database table prefix for security",
            example: "wp_",
          },
          {
            name: "WORDPRESS_DEBUG",
            required: false,
            description: "Enable debug logging — set to false in production",
            example: "false",
          },
        ],
      },

      dockerConfig: {
        baseImage: "wordpress:php8.3-apache",
        buildSteps: [
          "version: '3.8'",
          "services:",
          "  wordpress:",
          "    image: wordpress:php8.3-apache",
          "    ports:",
          "      - '80:80'",
          "    environment:",
          "      WORDPRESS_DB_HOST: db",
          "      WORDPRESS_DB_NAME: wordpress",
          "      WORDPRESS_DB_USER: wordpress",
          "      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}",
          "    volumes:",
          "      - wp_content:/var/www/html/wp-content",
          "  db:",
          "    image: mysql:8.0",
          "    environment:",
          "      MYSQL_DATABASE: wordpress",
          "      MYSQL_USER: wordpress",
          "      MYSQL_PASSWORD: ${DB_PASSWORD}",
          "      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}",
          "    volumes:",
          "      - db_data:/var/lib/mysql",
          "volumes:",
          "  wp_content:",
          "  db_data:",
        ],
        exposePort: 80,
        cmd: ["apache2-foreground"],
        dockerfileSnippet: [
          "# docker-compose.yml (recommended for WordPress)",
          "version: '3.8'",
          "services:",
          "  wordpress:",
          "    image: wordpress:php8.3-apache",
          "    ports: ['80:80']",
          "    environment:",
          "      WORDPRESS_DB_HOST: db",
          "      WORDPRESS_DB_NAME: wordpress",
          "      WORDPRESS_DB_USER: wordpress",
          "      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}",
          "    volumes:",
          "      - wp_content:/var/www/html/wp-content",
          "  db:",
          "    image: mysql:8.0",
          "    environment:",
          "      MYSQL_DATABASE: wordpress",
          "      MYSQL_USER: wordpress",
          "      MYSQL_PASSWORD: ${DB_PASSWORD}",
          "      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}",
          "    volumes:",
          "      - db_data:/var/lib/mysql",
          "volumes: {wp_content: {}, db_data: {}}",
        ].join("\n"),
      },

      ciConfig: {
        platform: "github-actions",
        filename: ".github/workflows/deploy.yml",
        content: [
          "name: Deploy WordPress",
          "on:",
          "  push:",
          "    branches: [main]",
          "jobs:",
          "  deploy:",
          "    runs-on: ubuntu-latest",
          "    steps:",
          "      - uses: actions/checkout@v4",
          "      - name: Sync theme/plugin files via rsync",
          "        run: |",
          "          rsync -avz --delete wp-content/ user@your-server:/var/www/html/wp-content/",
          "      - name: Run database migrations (if using WP-CLI)",
          "        run: |",
          "          ssh user@your-server 'wp db optimize && wp cache flush'",
          "      # Or: use WP Engine / Kinsta Git push deploy",
        ].join("\n"),
      },

      checklist: [
        "Generate fresh secret keys from https://api.wordpress.org/secret-key/1.1/salt/ and store them securely",
        "Set WORDPRESS_DEBUG=false and WP_DEBUG=false in production wp-config.php",
        "Install a caching plugin (WP Super Cache or W3 Total Cache) for static-file caching",
        "Enable a CDN (Cloudflare or your host's built-in CDN) for assets",
        "Back up the database and wp-content before every major update",
        "Limit login attempts — install a security plugin (Wordfence, Solid Security)",
        "Disable file editing in wp-admin: add `define('DISALLOW_FILE_EDIT', true)` to wp-config.php",
        "Use a staging environment to test plugin and core updates before applying to production",
      ],
    };
  },
};
