import type { AssemblyNavigation, AssemblyNavItem } from "@workspace/stencil-assembly-engine";

// ---------------------------------------------------------------------------
// generateNavHTML
// Renders the primary navigation as an HTML <nav> element.
// Supports one level of dropdowns for child items.
// ---------------------------------------------------------------------------

export function generateNavHTML(
  nav: AssemblyNavigation,
  siteTitle: string,
  currentRoute = "/"
): string {
  const logoHtml = `<a href="/" class="site-logo">${escapeHtml(siteTitle)}</a>`;

  const primaryLinks = nav.primaryNav
    .slice(0, 8)
    .map((item) => renderNavItem(item, currentRoute))
    .join("\n");

  return `${logoHtml}
<ul class="nav-links" role="list">
${primaryLinks}
</ul>`;
}

// ---------------------------------------------------------------------------
// generateFooterHTML
// Renders footer nav groups.
// ---------------------------------------------------------------------------

export function generateFooterHTML(nav: AssemblyNavigation, siteTitle: string): string {
  const year = new Date().getFullYear();

  const groups = nav.footerGroups
    .slice(0, 4)
    .map(
      (group) => `
    <div class="footer-group">
      <h4>${escapeHtml(group.label)}</h4>
      <ul>
        ${group.items.map((item) => `<li><a href="${escapeHtml(item.route)}">${escapeHtml(item.label)}</a></li>`).join("\n        ")}
      </ul>
    </div>`
    )
    .join("\n");

  const hasGroups = nav.footerGroups.length > 0;

  return `<div class="footer-inner">
${hasGroups ? groups : `<div class="footer-group"><h4>${escapeHtml(siteTitle)}</h4></div>`}
</div>
<div class="footer-bottom">
  <span>© ${year} ${escapeHtml(siteTitle)}</span>
  <span>Generated by Site Constructor</span>
</div>`;
}

// ---------------------------------------------------------------------------
// generateBreadcrumbsHTML
// ---------------------------------------------------------------------------

export function generateBreadcrumbsHTML(
  crumbs: Array<{ label: string; route: string }>,
  currentTitle: string
): string {
  if (!crumbs || crumbs.length === 0) return "";

  const items = crumbs.map(
    (c, i) =>
      `<span class="breadcrumb-link" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <a class="breadcrumb-link" href="${escapeHtml(c.route)}" itemprop="item"><span itemprop="name">${escapeHtml(c.label)}</span></a>
        <meta itemprop="position" content="${i + 1}" />
      </span>
      <span class="breadcrumb-sep" aria-hidden="true">›</span>`
  );

  return `<nav class="breadcrumbs" aria-label="Breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
  ${items.join("\n  ")}
  <span class="breadcrumb-current" aria-current="page">${escapeHtml(currentTitle)}</span>
</nav>`;
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

function renderNavItem(item: AssemblyNavItem, currentRoute: string): string {
  const isActive = item.route === currentRoute;
  const activeClass = isActive ? " active" : "";

  if (item.children.length > 0) {
    const children = item.children
      .slice(0, 6)
      .map(
        (child) =>
          `<li><a href="${escapeHtml(child.route)}" class="nav-link${child.route === currentRoute ? " active" : ""}">${escapeHtml(child.label)}</a></li>`
      )
      .join("\n");

    return `<li class="nav-has-children">
  <a href="${escapeHtml(item.route)}" class="nav-link${activeClass}">${escapeHtml(item.label)}</a>
  <ul class="nav-dropdown">
    ${children}
  </ul>
</li>`;
  }

  return `<li><a href="${escapeHtml(item.route)}" class="nav-link${activeClass}">${escapeHtml(item.label)}</a></li>`;
}

export function escapeHtml(str: string | null | undefined): string {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
