import { Router, type IRouter } from "express";
import apiCompatibilityBm5Router from "./api-compatibility-bm5.js";
import apiContractValidationD4Router from "./api-contract-validation-d4.js";
import assetIntelligenceC2Router from "./asset-intelligence-c2.js";
import authPreservationBm4Router from "./auth-preservation-bm4.js";
import backendDetectionD1Router from "./backend-detection-d1.js";
import brandDnaRouter from "./brand-dna.js";
import canonicalPipelineRouter from "./canonical-pipeline.js";
import certificationC6Router from "./certification-c6.js";
import colorEngineRouter from "./color-engine.js";
import compatibilityBm1Router from "./compatibility-bm1.js";
import componentExtractionRouter from "./component-extraction.js";
import componentMergeBm6Router from "./component-merge-bm6.js";
import consistencyVr6Router from "./consistency-vr6.js";
import dataBindingBm7Router from "./data-binding-bm7.js";
import databaseCompatibilityBm3Router from "./database-compatibility-bm3.js";
import decisionEngineRouter from "./decision-engine.js";
import deploymentExecutionRouter from "./deployment-execution.js";
import deploymentRouter from "./deployment.js";
import differentialRouter from "./differential.js";
import disasterRecoveryE4Router from "./disaster-recovery-e4.js";
import eventsRouter from "./events.js";
import executionPipelineRouter from "./execution-pipeline.js";
import failureRecoveryRouter from "./failure-recovery.js";
import healthRouter from "./health.js";
import humanOverrideRouter from "./human-override.js";
import humanReviewGateRouter from "./human-review-gate.js";
import incrementalRegenerationC1Router from "./incremental-regeneration-c1.js";
import jobsRouter from "./jobs.js";
import learningLoopValidationRouter from "./learning-loop-validation.js";
import loadTestE1Router from "./load-test-e1.js";
import masterOrchestrationRouter from "./master-orchestration.js";
import mergeCertificationD5Router from "./merge-certification-d5.js";
import mergeExecutionBm10Router from "./merge-execution-bm10.js";
import mergeExecutionD3Router from "./merge-execution-d3.js";
import mergeIntelligenceBm11Router from "./merge-intelligence-bm11.js";
import mergeIntelligenceRouter from "./merge-intelligence.js";
import mergeOrchestratorBm12Router from "./merge-orchestrator-bm12.js";
import mergeSimulationBm8Router from "./merge-simulation-bm8.js";
import monitoringPersistencePh5Router from "./monitoring-persistence-ph5.js";
import observabilityE3Router from "./observability-e3.js";
import oneClickReconstructionRouter from "./one-click-reconstruction.js";
import orchestrateRouter from "./orchestrate.js";
import orchestrationDashboardRouter from "./orchestration-dashboard.js";
import pipelineMonitoringPh2Router from "./pipeline-monitoring-ph2.js";
import pipelineStateMachineRouter from "./pipeline-state-machine.js";
import pixelComparisonRouter from "./pixel-comparison.js";
import platformCertificationRouter from "./platform-certification.js";
import platformValidationRouter from "./platform-validation.js";
import platformRouter from "./platform.js";
import primeIndexRouter from "./prime-index.js";
import productionCertificationE5Router from "./production-certification-e5.js";
import productionReadinessRouter from "./production-readiness.js";
import progressRouter from "./progress.js";
import qualityMonitoringRouter from "./quality-monitoring.js";
import reconstructionLoopVr8Router from "./reconstruction-loop-vr8.js";
import reconstructionValueRi2Router from "./reconstruction-value-ri2.js";
import recoveryRouter from "./recovery.js";
import regressionValidationPh3Router from "./regression-validation-ph3.js";
import resourceDecisionRi3Router from "./resource-decision-ri3.js";
import rollbackGeneratorBm9Router from "./rollback-generator-bm9.js";
import routeCollisionBm2Router from "./route-collision-bm2.js";
import runtimeOptimizerC5Router from "./runtime-optimizer-c5.js";
import runtimePerformanceC3Router from "./runtime-performance-c3.js";
import screenshotCaptureRouter from "./screenshot-capture.js";
import screenshotVisualDnaRouter from "./screenshot-visual-dna.js";
import securityHardeningE2Router from "./security-hardening-e2.js";
import semanticMergeD2Router from "./semantic-merge-d2.js";
import seoIntelligenceC4Router from "./seo-intelligence-c4.js";
import supervisorRouter from "./supervisor.js";
import typographyFidelityB6Router from "./typography-fidelity-b6.js";
import visualCertificationB8Router from "./visual-certification-b8.js";
import visualDiffLocalizerRouter from "./visual-diff-localizer.js";
import visualFidelityVr7Router from "./visual-fidelity-vr7.js";
import visualOptimizationLoopB7Router from "./visual-optimization-loop-b7.js";
import visualOptimizerRouter from "./visual-optimizer.js";
import visualSchemaRouter from "./visual-schema.js";
import visualStencilMapperVr5Router from "./visual-stencil-mapper-vr5.js";
import vr8ReviewIntegrationRouter from "./vr8-review-integration.js";
import storageRouter from "./storage.js";
import regenerateRouter from "./regenerate.js";
import jobStorageRouter from "./job-storage.js";

const router: IRouter = Router();

router.use(apiCompatibilityBm5Router);
router.use(apiContractValidationD4Router);
router.use(assetIntelligenceC2Router);
router.use(authPreservationBm4Router);
router.use(backendDetectionD1Router);
router.use(brandDnaRouter);
router.use(canonicalPipelineRouter);
router.use(certificationC6Router);
router.use(colorEngineRouter);
router.use(compatibilityBm1Router);
router.use(componentExtractionRouter);
router.use(componentMergeBm6Router);
router.use(consistencyVr6Router);
router.use(dataBindingBm7Router);
router.use(databaseCompatibilityBm3Router);
router.use(decisionEngineRouter);
router.use(deploymentExecutionRouter);
router.use(deploymentRouter);
router.use(differentialRouter);
router.use(disasterRecoveryE4Router);
router.use(eventsRouter);
router.use(executionPipelineRouter);
router.use(failureRecoveryRouter);
router.use(healthRouter);
router.use(humanOverrideRouter);
router.use(humanReviewGateRouter);
router.use(incrementalRegenerationC1Router);
router.use(jobsRouter);
router.use(learningLoopValidationRouter);
router.use(loadTestE1Router);
router.use(masterOrchestrationRouter);
router.use(mergeCertificationD5Router);
router.use(mergeExecutionBm10Router);
router.use(mergeExecutionD3Router);
router.use(mergeIntelligenceBm11Router);
router.use(mergeIntelligenceRouter);
router.use(mergeOrchestratorBm12Router);
router.use(mergeSimulationBm8Router);
router.use(monitoringPersistencePh5Router);
router.use(observabilityE3Router);
router.use(oneClickReconstructionRouter);
router.use(orchestrateRouter);
router.use(orchestrationDashboardRouter);
router.use(pipelineMonitoringPh2Router);
router.use(pipelineStateMachineRouter);
router.use(pixelComparisonRouter);
router.use(platformCertificationRouter);
router.use(platformValidationRouter);
router.use(platformRouter);
router.use(primeIndexRouter);
router.use(productionCertificationE5Router);
router.use(productionReadinessRouter);
router.use(progressRouter);
router.use(qualityMonitoringRouter);
router.use(reconstructionLoopVr8Router);
router.use(reconstructionValueRi2Router);
router.use(recoveryRouter);
router.use(regressionValidationPh3Router);
router.use(resourceDecisionRi3Router);
router.use(rollbackGeneratorBm9Router);
router.use(routeCollisionBm2Router);
router.use(runtimeOptimizerC5Router);
router.use(runtimePerformanceC3Router);
router.use(screenshotCaptureRouter);
router.use(screenshotVisualDnaRouter);
router.use(securityHardeningE2Router);
router.use(semanticMergeD2Router);
router.use(seoIntelligenceC4Router);
router.use(supervisorRouter);
router.use(typographyFidelityB6Router);
router.use(visualCertificationB8Router);
router.use(visualDiffLocalizerRouter);
router.use(visualFidelityVr7Router);
router.use(visualOptimizationLoopB7Router);
router.use(visualOptimizerRouter);
router.use(visualSchemaRouter);
router.use(visualStencilMapperVr5Router);
router.use(vr8ReviewIntegrationRouter);
router.use(storageRouter);
router.use(regenerateRouter);
router.use(jobStorageRouter);

export default router;
