/**
 * docker.ts — Phase 6.1 Deployment Target: Docker
 *
 * Generates a production-grade Docker setup for the full stack:
 *   - Dockerfile          (multi-stage: build + minimal runtime)
 *   - docker-compose.yml  (API + Postgres + optional Nginx)
 *   - .dockerignore
 *   - nginx/default.conf  (reverse proxy: / → frontend, /api → backend)
 *   - .env.docker.example
 *   - .github/workflows/docker-deploy.yml
 */

import type { TargetAdapter, TargetPlan, EnvironmentProfile } from "./types.js";

export const dockerAdapter: TargetAdapter = {
  target: "docker",

  generate(sourceUrl: string, env: EnvironmentProfile): TargetPlan {
    const now = new Date().toISOString();
    const hasDb = env.database.detected;
    const hasR2 = env.storage.detected;
    const nodeVer = env.nodeVersion.split(".")[0] ?? "22";
    const missingVars = env.envVars.filter((v) => v.required && !v.detected);

    const dockerfile = [
      `# ─── Stage 1: Install dependencies ───────────────────────────────────────`,
      `FROM node:${nodeVer}-alpine AS deps`,
      `WORKDIR /app`,
      `RUN npm install -g pnpm@10`,
      `COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./`,
      `COPY lib/*/package.json ./lib/`,
      `COPY artifacts/api-server/package.json ./artifacts/api-server/`,
      `COPY artifacts/article-scraper/package.json ./artifacts/article-scraper/`,
      `RUN pnpm install --frozen-lockfile`,
      ``,
      `# ─── Stage 2: Build ───────────────────────────────────────────────────────`,
      `FROM deps AS builder`,
      `COPY . .`,
      `RUN pnpm run typecheck:libs`,
      `RUN pnpm --filter @workspace/api-server run build`,
      `RUN pnpm --filter @workspace/article-scraper run build`,
      ``,
      `# ─── Stage 3: Runtime (minimal) ───────────────────────────────────────────`,
      `FROM node:${nodeVer}-alpine AS runtime`,
      ``,
      `# Puppeteer / Chromium dependencies`,
      `RUN apk add --no-cache \\`,
      `    chromium \\`,
      `    nss \\`,
      `    freetype \\`,
      `    harfbuzz \\`,
      `    ca-certificates \\`,
      `    ttf-freefont`,
      ``,
      `ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser`,
      `ENV PUPPETEER_SKIP_DOWNLOAD=true`,
      ``,
      `WORKDIR /app`,
      `RUN npm install -g pnpm@10`,
      ``,
      `# Copy only production artifacts`,
      `COPY --from=builder /app/artifacts/api-server/dist ./artifacts/api-server/dist`,
      `COPY --from=builder /app/artifacts/api-server/package.json ./artifacts/api-server/`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/artifacts/api-server/node_modules ./artifacts/api-server/node_modules`,
      ``,
      `EXPOSE 8080`,
      `ENV NODE_ENV=production`,
      `ENV PORT=8080`,
      ``,
      `HEALTHCHECK --interval=30s --timeout=10s --start-period=20s \\`,
      `  CMD wget -qO- http://localhost:8080/api/healthz || exit 1`,
      ``,
      `CMD ["node", "--enable-source-maps", "--max-old-space-size=768", \\`,
      `     "artifacts/api-server/dist/index.mjs"]`,
    ].join("\n");

    const dockerCompose = [
      `version: "3.9"`,
      ``,
      `services:`,
      `  api:`,
      `    build:`,
      `      context: .`,
      `      dockerfile: Dockerfile`,
      `      target: runtime`,
      `    restart: unless-stopped`,
      `    ports:`,
      `      - "8080:8080"`,
      `    environment:`,
      `      NODE_ENV: production`,
      `      PORT: "8080"`,
      `      DATABASE_URL: \${DATABASE_URL}`,
      `      SESSION_SECRET: \${SESSION_SECRET}`,
      `      CLOUD_PROVIDER: \${CLOUD_PROVIDER:-r2}`,
      `      R2_ACCOUNT_ID: \${R2_ACCOUNT_ID}`,
      `      R2_ACCESS_KEY_ID: \${R2_ACCESS_KEY_ID}`,
      `      R2_SECRET_ACCESS_KEY: \${R2_SECRET_ACCESS_KEY}`,
      `      R2_BUCKET_NAME: \${R2_BUCKET_NAME:-assets-stencil}`,
      `      R2_PUBLIC_BASE_URL: \${R2_PUBLIC_BASE_URL}`,
      `      R2_ENDPOINT: \${R2_ENDPOINT}`,
      `    depends_on:`,
      `      db:`,
      `        condition: service_healthy`,
      `    volumes:`,
      `      - /tmp/webrecon:/tmp`,
      ``,
      `  frontend:`,
      `    image: nginx:alpine`,
      `    restart: unless-stopped`,
      `    ports:`,
      `      - "3000:80"`,
      `    volumes:`,
      `      - ./artifacts/article-scraper/dist:/usr/share/nginx/html:ro`,
      `      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro`,
      `    depends_on:`,
      `      - api`,
      ``,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    restart: unless-stopped`,
      `    environment:`,
      `      POSTGRES_DB: webrecon`,
      `      POSTGRES_USER: webrecon`,
      `      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-changeme}`,
      `    volumes:`,
      `      - postgres_data:/var/lib/postgresql/data`,
      `    healthcheck:`,
      `      test: ["CMD-SHELL", "pg_isready -U webrecon"]`,
      `      interval: 10s`,
      `      timeout: 5s`,
      `      retries: 5`,
      ``,
      `volumes:`,
      `  postgres_data:`,
    ].join("\n");

    const nginxConf = [
      `server {`,
      `    listen 80;`,
      `    server_name _;`,
      ``,
      `    # API — proxy to Express`,
      `    location /api/ {`,
      `        proxy_pass         http://api:8080;`,
      `        proxy_http_version 1.1;`,
      `        proxy_set_header   Host              $host;`,
      `        proxy_set_header   X-Real-IP         $remote_addr;`,
      `        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;`,
      `        proxy_set_header   X-Forwarded-Proto $scheme;`,
      `        proxy_read_timeout 120s;`,
      `    }`,
      ``,
      `    # Frontend — serve Vite static build`,
      `    location / {`,
      `        root  /usr/share/nginx/html;`,
      `        index index.html;`,
      `        try_files $uri $uri/ /index.html;`,
      `        expires 1d;`,
      `        add_header Cache-Control "public, immutable";`,
      `    }`,
      ``,
      `    # Health check`,
      `    location /health {`,
      `        return 200 "ok\\n";`,
      `        add_header Content-Type text/plain;`,
      `    }`,
      `}`,
    ].join("\n");

    const dockerignore = [
      `node_modules`,
      `.git`,
      `*.log`,
      `.env`,
      `.env.*`,
      `!.env.*.example`,
      `dist`,
      `*.tsbuildinfo`,
      `.merge-archive`,
      `backend-analysis-report.json`,
      `merge-plan.json`,
      `merge-audit.json`,
      `deployment-plan.json`,
      `June20thwebrecon`,
    ].join("\n");

    const envExample = [
      `# Web Reconstruction Platform — Docker Environment`,
      `# Copy to .env (never commit this file)`,
      ``,
      `# PostgreSQL (docker-compose provisions this — use the connection string below)`,
      `DATABASE_URL=postgresql://webrecon:changeme@db:5432/webrecon`,
      `POSTGRES_PASSWORD=changeme`,
      ``,
      `SESSION_SECRET=change-me-long-random-string`,
      ``,
      `# Cloudflare R2`,
      `CLOUD_PROVIDER=r2`,
      `R2_ACCOUNT_ID=your-account-id`,
      `R2_ACCESS_KEY_ID=your-access-key`,
      `R2_SECRET_ACCESS_KEY=your-secret-key`,
      `R2_BUCKET_NAME=assets-stencil`,
      `R2_PUBLIC_BASE_URL=https://pub-xxx.r2.dev`,
      `R2_ENDPOINT=https://your-account-id.r2.cloudflarestorage.com`,
    ].join("\n");

    const ciYaml = [
      `name: Build & Push Docker Image`,
      `on:`,
      `  push:`,
      `    branches: [main]`,
      `    tags: ['v*']`,
      ``,
      `jobs:`,
      `  build-and-push:`,
      `    runs-on: ubuntu-latest`,
      `    permissions:`,
      `      contents: read`,
      `      packages: write`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: docker/setup-buildx-action@v3`,
      `      - name: Log in to GitHub Container Registry`,
      `        uses: docker/login-action@v3`,
      `        with:`,
      `          registry: ghcr.io`,
      `          username: \${{ github.actor }}`,
      `          password: \${{ secrets.GITHUB_TOKEN }}`,
      `      - name: Build and push`,
      `        uses: docker/build-push-action@v5`,
      `        with:`,
      `          context: .`,
      `          push: true`,
      `          tags: ghcr.io/\${{ github.repository }}:latest`,
      `          cache-from: type=gha`,
      `          cache-to: type=gha,mode=max`,
    ].join("\n");

    return {
      version: "1.0",
      target: "docker",
      targetLabel: "Docker (self-hosted / any cloud)",
      generatedAt: now,
      sourceUrl,
      summary:
        "Fully containerised deployment: multi-stage Dockerfile with Chromium/Puppeteer support, Nginx reverse proxy for the React frontend, and docker-compose for the full stack including Postgres. Deploy anywhere that runs Docker — Railway, Render, Fly.io, DigitalOcean, AWS ECS, or your own server.",
      tier: "free",
      recommended: true,
      confidence: "high",
      files: [
        {
          path: "Dockerfile",
          content: dockerfile,
          description: "Multi-stage Dockerfile: deps → builder → minimal runtime with Chromium pre-installed",
        },
        {
          path: "docker-compose.yml",
          content: dockerCompose,
          description: "Full stack compose: API server + Nginx frontend + PostgreSQL with health checks",
        },
        {
          path: "nginx/default.conf",
          content: nginxConf,
          description: "Nginx reverse proxy: routes /api/* to Express, /* to the React static build",
        },
        {
          path: ".dockerignore",
          content: dockerignore,
          description: "Excludes dev artifacts, secrets, and large analysis reports from the Docker build context",
        },
        {
          path: ".env.docker.example",
          content: envExample,
          description: "Template .env for docker-compose — copy to .env and fill in your values",
        },
        {
          path: ".github/workflows/docker-deploy.yml",
          content: ciYaml,
          description: "GitHub Actions: builds and pushes Docker image to GitHub Container Registry on push to main",
        },
      ],
      envVars: env.envVars,
      deploySteps: [
        {
          order: 1,
          title: "Copy and configure environment",
          command: "cp .env.docker.example .env && nano .env",
          notes: [
            "Fill in DATABASE_URL, SESSION_SECRET, and R2 credentials",
            "POSTGRES_PASSWORD is used by both the db service and DATABASE_URL",
          ],
        },
        {
          order: 2,
          title: "Build the frontend",
          command: "pnpm --filter @workspace/article-scraper run build",
          notes: ["The Nginx container serves the static build from artifacts/article-scraper/dist/"],
        },
        {
          order: 3,
          title: "Build and start all services",
          command: "docker compose up -d --build",
          notes: [
            "First build takes ~5 minutes (downloads Chromium)",
            "Subsequent builds use layer cache (~2 minutes)",
            "Wait for: db (healthy) → api (healthy) → frontend",
          ],
        },
        {
          order: 4,
          title: "Run database migrations",
          command: "docker compose exec api node -e \"require('./dist/index.mjs')\" || DATABASE_URL=<url> pnpm --filter @workspace/db run push",
          notes: [
            hasDb ? "DATABASE_URL configured — run push to apply schema" : "Use the docker-compose Postgres or your own database",
            "Only needed on first deploy or when schema changes",
          ],
        },
        {
          order: 5,
          title: "Verify deployment",
          command: "curl http://localhost:8080/api/healthz && curl http://localhost:3000",
          notes: [
            "API: http://localhost:8080/api",
            "Frontend: http://localhost:3000",
            "R2 health: http://localhost:8080/api/healthz/r2",
          ],
        },
      ],
      estimatedDeployTime: "5–8 minutes (first build with Chromium download)",
      limitations: [
        "Chromium download (~300MB) makes first build slow — use a cached base image in production",
        "Puppeteer requires elevated memory — allocate at least 1GB RAM to the API container",
        "docker-compose Postgres is ephemeral without a named volume — always use the volumes: block",
        "For production, use an external managed Postgres (not the compose db service) for reliability",
      ],
      checklist: [
        missingVars.length > 0
          ? `⚠ Missing env vars: ${missingVars.map((v) => v.key).join(", ")}`
          : "✓ All required env vars detected",
        "Copy .env.docker.example to .env and fill in secrets",
        "Build frontend: pnpm --filter @workspace/article-scraper run build",
        "mkdir -p nginx && copy nginx/default.conf",
        hasR2 ? "✓ R2 configured — assets persist across container restarts" : "⚠ Configure R2 to avoid data loss on restart",
        "Verify: docker compose ps (all services healthy)",
        "Healthcheck: GET /api/healthz → {status: 'ok'}",
      ],
    };
  },
};
