/**
 * theme-generator.ts
 *
 * Converts DesignTokens → two CSS files:
 *   src/theme/tokens.css  — all CSS custom properties
 *   src/theme/global.css  — reset, base typography, layout helpers
 *
 * Every token becomes a --token-name: value; CSS custom property on :root.
 * Dark mode tokens are gated on [data-theme="dark"].
 */

import type { DesignTokens } from "@workspace/theme-intelligence";
import type { PrimeFile } from "./types.js";

const COLOR_SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"] as const;

function colorScaleToVars(name: string, scale: Record<string, string>): string {
  return COLOR_SHADES.filter((s) => s in scale)
    .map((shade) => `  --color-${name}-${shade}: ${scale[shade]};`)
    .join("\n");
}

function semanticToVars(prefix: string, semantic: Record<string, string>): string {
  return Object.entries(semantic)
    .map(([k, v]) => `  --${prefix}-${camelToKebab(k)}: ${v};`)
    .join("\n");
}

function camelToKebab(s: string): string {
  return s.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`);
}

function recordToVars(prefix: string, record: Record<string, string | number>): string {
  return Object.entries(record)
    .map(([k, v]) => `  --${prefix}-${camelToKebab(String(k))}: ${v};`)
    .join("\n");
}

export function generateThemeFiles(tokens: DesignTokens): PrimeFile[] {
  const { colors, typography, spacing, radius, shadows, animation, layout } = tokens;

  let cssVarCount = 0;

  // ── Color scales ──────────────────────────────────────────────────────────
  const colorScaleVars = (["primary", "secondary", "accent", "neutral"] as const)
    .map((name) => colorScaleToVars(name, colors[name] as unknown as Record<string, string>))
    .join("\n");

  const semanticVars = semanticToVars("color", colors.semantic as unknown as Record<string, string>);

  // ── Typography ─────────────────────────────────────────────────────────────
  const typographyVars = [
    `  --font-heading: ${typography.fontFamilies.heading};`,
    `  --font-body: ${typography.fontFamilies.body};`,
    `  --font-display: ${typography.fontFamilies.display};`,
    `  --font-mono: ${typography.fontFamilies.mono};`,
    recordToVars("text", typography.fontSizes as Record<string, string>),
    recordToVars("font-weight", typography.fontWeights as Record<string, number>),
    recordToVars("leading", typography.lineHeights as Record<string, string>),
    recordToVars("tracking", typography.letterSpacing as Record<string, string>),
  ].join("\n");

  // ── Spacing ────────────────────────────────────────────────────────────────
  const spacingVars = Object.entries(spacing)
    .filter(([, v]) => typeof v === "string")
    .map(([k, v]) => `  --space-${String(k).replace(".", "_")}: ${v};`)
    .join("\n");

  // ── Radius ────────────────────────────────────────────────────────────────
  const radiusVars = Object.entries(radius)
    .map(([k, v]) => `  --radius-${camelToKebab(k)}: ${v};`)
    .join("\n");

  // ── Shadows ───────────────────────────────────────────────────────────────
  const shadowVars = Object.entries(shadows)
    .map(([k, v]) => `  --shadow-${k}: ${v};`)
    .join("\n");

  // ── Animation ─────────────────────────────────────────────────────────────
  const animVars = Object.entries(animation)
    .map(([k, v]) => `  --anim-${camelToKebab(k)}: ${v};`)
    .join("\n");

  // ── Layout ────────────────────────────────────────────────────────────────
  const layoutVars = [
    `  --layout-container-max: ${layout.containerMaxWidth};`,
    `  --layout-content-max: ${layout.contentMaxWidth};`,
    `  --layout-sidebar-width: ${layout.sidebarWidth};`,
    `  --layout-grid-columns: ${layout.gridColumns};`,
    `  --layout-grid-gap: ${layout.gridGap};`,
  ].join("\n");

  // ── Dark mode overrides ───────────────────────────────────────────────────
  const darkModeVars = semanticToVars("color", colors.darkMode as unknown as Record<string, string>);

  const tokensCss = `/**
 * tokens.css — Website Prime design tokens
 * Auto-generated by Phase 5.1 Website Prime Generator
 * Do not edit manually.
 */

:root {
  /* ── Color scales ─────────────────────────────────── */
${colorScaleVars}

  /* ── Semantic colors ──────────────────────────────── */
${semanticVars}

  /* ── Typography ───────────────────────────────────── */
${typographyVars}

  /* ── Spacing ──────────────────────────────────────── */
${spacingVars}

  /* ── Border radius ────────────────────────────────── */
${radiusVars}

  /* ── Shadows ──────────────────────────────────────── */
${shadowVars}

  /* ── Animation ────────────────────────────────────── */
${animVars}

  /* ── Layout ───────────────────────────────────────── */
${layoutVars}
}

[data-theme="dark"] {
${darkModeVars}
}
`;

  cssVarCount = (tokensCss.match(/--[a-z]/g) ?? []).length;

  const globalCss = `/**
 * global.css — Website Prime base styles
 * Uses CSS custom properties from tokens.css
 */

@import './tokens.css';

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-size: 16px;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  scroll-behavior: smooth;
}

body {
  font-family: var(--font-body, system-ui, sans-serif);
  background-color: var(--color-background, #ffffff);
  color: var(--color-text-primary, #111827);
  line-height: 1.6;
  min-height: 100vh;
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading, system-ui, sans-serif);
  font-weight: var(--font-weight-bold, 700);
  line-height: var(--leading-tight, 1.25);
  color: var(--color-text-primary, #111827);
}

a {
  color: var(--color-link, var(--color-primary-600, #2563eb));
  text-decoration: none;
  transition: color var(--anim-duration-fast, 150ms) var(--anim-easing-default, ease);
}

a:hover {
  color: var(--color-link-hover, var(--color-primary-700, #1d4ed8));
  text-decoration: underline;
}

img, video {
  max-width: 100%;
  display: block;
}

code, pre {
  font-family: var(--font-mono, 'Fira Code', monospace);
}

.container {
  max-width: var(--layout-container-max, 1280px);
  margin-inline: auto;
  padding-inline: var(--space-4, 1rem);
}

.content-container {
  max-width: var(--layout-content-max, 720px);
  margin-inline: auto;
  padding-inline: var(--space-4, 1rem);
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.skip-link {
  position: absolute;
  top: -100%;
  left: var(--space-4, 1rem);
  background: var(--color-primary-600, #2563eb);
  color: #fff;
  padding: var(--space-2, 0.5rem) var(--space-4, 1rem);
  border-radius: var(--radius-md, 0.375rem);
  z-index: 9999;
}

.skip-link:focus {
  top: var(--space-4, 1rem);
}
`;

  return [
    { path: "src/theme/tokens.css", content: tokensCss, kind: "css" },
    { path: "src/theme/global.css", content: globalCss, kind: "css" },
  ];
}
