import type { DeploymentAdapter, DeploymentContext, DeploymentPlan } from "../types.js";

export const laravelAdapter: DeploymentAdapter = {
  framework: "laravel",

  generate(ctx: DeploymentContext): DeploymentPlan {
    const now = new Date().toISOString();
    return {
      version: "1.0",
      generatedAt: now,
      framework: "laravel",
      frameworkVersion: ctx.version,
      sourceUrl: ctx.sourceUrl,
      summary:
        "Laravel PHP application — Laravel Forge manages production VPS servers with zero-downtime deploys. Vapor provides serverless AWS deployment. Docker enables self-hosting on any cloud.",

      hostingOptions: [
        {
          name: "Laravel Forge",
          provider: "forge.laravel.com",
          tier: "pro",
          url: "https://forge.laravel.com",
          recommended: true,
          deployMethod: "panel",
          config: {
            phpVersion: "8.3",
            webServer: "nginx",
            database: "mysql8",
          },
          notes: [
            "Provisions and manages VPS servers on DigitalOcean, AWS, Linode, or Vultr.",
            "Zero-downtime deployment via atomic releases.",
            "Automated SSL (Let's Encrypt), queue workers, and schedulers.",
          ],
        },
        {
          name: "Laravel Vapor",
          provider: "vapor.laravel.com",
          tier: "pro",
          url: "https://vapor.laravel.com",
          recommended: false,
          deployMethod: "cli",
          config: {
            runtime: "php-8.3:al2",
            memory: "512",
            queue: "sqs",
            cache: "elasticache",
          },
          notes: [
            "Serverless deployment on AWS Lambda — scales to zero.",
            "Requires Vapor subscription and AWS account.",
            "Run `vapor deploy production` to deploy.",
            "Queues use SQS; sessions/cache use DynamoDB or ElastiCache.",
          ],
        },
        {
          name: "Railway",
          provider: "railway",
          tier: "hobby",
          url: "https://railway.app",
          recommended: false,
          deployMethod: "docker",
          config: {
            buildCommand: "composer install --no-dev --optimize-autoloader && php artisan optimize",
            startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT",
          },
          notes: [
            "Deploy via Docker for full PHP control.",
            "Add a MySQL or Postgres service to the same Railway project.",
            "Run migrations in the deploy command: `php artisan migrate --force`.",
          ],
        },
        {
          name: "Render",
          provider: "render",
          tier: "hobby",
          url: "https://render.com",
          recommended: false,
          deployMethod: "docker",
          config: {
            dockerfilePath: "./Dockerfile",
            healthCheckPath: "/up",
          },
          notes: [
            "Use the official Laravel Docker image or build your own.",
            "Add a managed Postgres database to the same Render project.",
          ],
        },
        {
          name: "VPS (Ubuntu + nginx + PHP-FPM)",
          provider: "self-hosted",
          tier: "pro",
          url: "https://laravel.com/docs/deployment",
          recommended: false,
          deployMethod: "cli",
          config: {
            webRoot: "/var/www/html/public",
            phpVersion: "8.3-fpm",
            supervisor: "queue:work",
          },
          notes: [
            "Use Laravel Deployer or Capistrano for zero-downtime releases.",
            "Configure Supervisor to keep queue workers running.",
            "Set up a cron job: `* * * * * php /var/www/html/artisan schedule:run`.",
          ],
        },
      ],

      buildConfig: {
        installCommand: "composer install --no-dev --optimize-autoloader",
        buildCommand: [
          "php artisan key:generate --force",
          "php artisan config:cache",
          "php artisan route:cache",
          "php artisan view:cache",
          "php artisan optimize",
          "npm ci && npm run build",
        ].join(" && "),
        outputDirectory: "public",
        startCommand: "php-fpm",
        nodeVersion: "20",
        phpVersion: "8.3",
        envVars: [
          {
            name: "APP_KEY",
            required: true,
            description: "Laravel application encryption key — generate with: php artisan key:generate --show",
            example: "base64:...",
          },
          {
            name: "APP_ENV",
            required: true,
            description: "Application environment",
            example: "production",
          },
          {
            name: "APP_URL",
            required: true,
            description: "Full URL of your production app",
            example: "https://your-app.com",
          },
          {
            name: "DB_CONNECTION",
            required: true,
            description: "Database driver",
            example: "mysql",
          },
          {
            name: "DB_HOST",
            required: true,
            description: "Database host",
            example: "127.0.0.1",
          },
          {
            name: "DB_DATABASE",
            required: true,
            description: "Database name",
            example: "laravel",
          },
          {
            name: "DB_USERNAME",
            required: true,
            description: "Database username",
            example: "laravel",
          },
          {
            name: "DB_PASSWORD",
            required: true,
            description: "Database password",
            example: null,
          },
          {
            name: "CACHE_DRIVER",
            required: false,
            description: "Cache backend: file, redis, memcached, database",
            example: "redis",
          },
          {
            name: "QUEUE_CONNECTION",
            required: false,
            description: "Queue backend for background jobs",
            example: "redis",
          },
          {
            name: "MAIL_MAILER",
            required: false,
            description: "Mail transport driver",
            example: "smtp",
          },
        ],
      },

      dockerConfig: {
        baseImage: "php:8.3-fpm-alpine",
        buildSteps: [
          "FROM php:8.3-fpm-alpine AS base",
          "RUN apk add --no-cache nginx supervisor curl unzip",
          "RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql opcache",
          "COPY --from=composer:2 /usr/bin/composer /usr/bin/composer",
          "",
          "FROM base AS builder",
          "WORKDIR /app",
          "COPY composer.json composer.lock ./",
          "RUN composer install --no-dev --optimize-autoloader --no-scripts",
          "COPY . .",
          "RUN php artisan optimize",
          "",
          "FROM base AS runner",
          "WORKDIR /var/www/html",
          "COPY --from=builder /app .",
          "COPY docker/nginx.conf /etc/nginx/nginx.conf",
          "COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf",
          "RUN chown -R www-data:www-data storage bootstrap/cache",
        ],
        exposePort: 80,
        cmd: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"],
        dockerfileSnippet: [
          "FROM php:8.3-fpm-alpine",
          "RUN apk add --no-cache nginx supervisor",
          "RUN docker-php-ext-install pdo pdo_mysql opcache",
          "COPY --from=composer:2 /usr/bin/composer /usr/bin/composer",
          "WORKDIR /var/www/html",
          "COPY composer.json composer.lock ./",
          "RUN composer install --no-dev --optimize-autoloader",
          "COPY . .",
          "RUN php artisan optimize",
          "RUN chown -R www-data:www-data storage bootstrap/cache",
          "EXPOSE 80",
          'CMD ["/usr/bin/supervisord", "-n"]',
        ].join("\n"),
      },

      ciConfig: {
        platform: "github-actions",
        filename: ".github/workflows/deploy.yml",
        content: [
          "name: Deploy Laravel App",
          "on:",
          "  push:",
          "    branches: [main]",
          "jobs:",
          "  test-and-deploy:",
          "    runs-on: ubuntu-latest",
          "    steps:",
          "      - uses: actions/checkout@v4",
          "      - uses: shivammathur/setup-php@v2",
          "        with:",
          "          php-version: '8.3'",
          "          extensions: pdo, pdo_mysql, mbstring, xml, bcmath",
          "      - run: composer install --no-dev --optimize-autoloader",
          "      - run: cp .env.example .env && php artisan key:generate",
          "      - run: php artisan test",
          "      # Add your deploy step: ssh + php artisan migrate --force, or vapor deploy",
        ].join("\n"),
      },

      checklist: [
        "Generate APP_KEY with `php artisan key:generate --show` and store it as a secret",
        "Run `php artisan migrate --force` as part of your deploy script",
        "Enable OPcache in php.ini for 3–5× performance improvement",
        "Run `php artisan optimize` (config:cache, route:cache, view:cache) after every deploy",
        "Configure Supervisor to keep queue workers (`php artisan queue:work`) alive",
        "Set up a cron job for the Laravel task scheduler",
        "Point nginx `root` to the `/public` directory — never expose the project root",
        "Set file permissions: `chmod -R 775 storage bootstrap/cache`",
      ],
    };
  },
};
